Repository certbot/website, pull requests merged in 2020-09, with the labels that each got.

#640 Add a note to help snap users configure PATH under all shells and sudo
  .gitignore
  _scripts/instruction-widget/install.js
  _scripts/instruction-widget/templates/install/preparecertbotsnapcommand.html
  _scripts/instruction-widget/templates/install/snap.html
Labels: area: snaps

#648 Move instructions for Arch Linux, openSUSE, and other UNIX to snaps
  _data/inputs.json
  _scripts/instruction-widget/install.js
Labels: priority: high

#650 Update snap instructions to ensure snapd is up to date
  _scripts/instruction-widget/templates/install/snap.html
Labels: area: snaps

#649 Update hosting_providers.json
  _data/hosting_providers.json
Labels: area: hosting providers
