Repository certbot/website, pull requests merged in 2020-10, with the labels that each got.

#659 Instruct RHEL to use snaps when possible
  _scripts/instruction-widget/install.js
Labels: area: fedora / redhat / CentOS, area: snaps, priority: significant

#658 Update Debian instructions to snaps
  _scripts/instruction-widget/install.js
Labels: area: snaps, instruction generator, priority: high

#661 Add extra explanation to wildcard glossary about base domain
  _terms/wildcard-certificate.md
Labels: docs
