Repository certbot/website, pull requests merged in 2020-08, with the labels that each got.

#627 Switch our Ubuntu instructions to our snap instructions
  _scripts/instruction-widget/install.js
Labels: area: snaps

#628 Switch to Python 3 and stop using certbot-auto
  Dockerfile
  _docs.sh
Labels: area: certbot-auto

#629 Update to a supported version of Python
  .travis.yml
Labels: enhancement

#613 Document how to install DNS plugin snaps
  _scripts/instruction-widget/install.js
  _scripts/instruction-widget/templates/install/installcertbotwildcard.html
  _scripts/instruction-widget/templates/install/snap.html
Labels: instruction generator

#632 adding "return" to instructions function
  _scripts/instruction-widget/main.js
Labels: instruction generator
