Repository certbot/website, pull requests merged in 2020-04, with the labels that each got.

#529 Added ICDSoft to the list of providers
  _data/hosting_providers.json
Labels: priority: unplanned

#548 Make instruction generator links use HTTPS
  _scripts/instruction-widget/templates/install/macos.html
  _scripts/main.js
Labels: security

#550 Fix link to other clients
  _faq_entries/8-OS.md
Labels: docs

#551 Simplify OpenBSD instructions
  _data/inputs.json
  _scripts/instruction-widget/install.js
Labels: docs

#553 Correct IRC channel
  privacy/index.md
Labels: docs

#555 Default to certbot and fix macOS instructions
  _scripts/instruction-widget/instructions.js
Labels: docs

#560 Remove architecture warning from Docker instructions.
  _scripts/instruction-widget/templates/install/centos.html
Labels: docs

#556 Don't modify cron/systemd directly
  _scripts/instruction-widget/templates/getting-started/renewal.html
Labels: docs

#558 Add basic snap installation instructions
  _data/inputs.json
  _scripts/instruction-widget/install.js
  _scripts/instruction-widget/templates/install/snap.html
Labels: area: snaps, docs

#564 Remove link to gantt chart
  _includes/contrib/main_list.html
Labels: docs

#562 Fix newer Ubuntu instructions
  _data/inputs.json
  _scripts/instruction-widget/install.js
  _scripts/instruction-widget/templates/install/ubuntu.html
Labels: instruction generator

#569 Make sure universe is enabled in non-PPA Ubuntu instructions
  _scripts/instruction-widget/templates/install/ubuntu.html
Labels: docs, priority: significant
