Repository certbot/website, pull requests merged in 2020-07, with the labels that each got.

#607 Remove version from Fedora dropdown
  _data/inputs.json
Labels: area: fedora / redhat / CentOS, area: pkging

#615 Add a note about snap multiarch support
  _scripts/instruction-widget/templates/install/snap.html
Labels: area: snaps

#620 Make Travis instructions more visible
  README.md
Labels: docs

#623 The Certbot snap is stable
  _scripts/instruction-widget/install.js
  _scripts/instruction-widget/templates/install/arch.html
  _scripts/instruction-widget/templates/install/centos.html
  _scripts/instruction-widget/templates/install/debian.html
  _scripts/instruction-widget/templates/install/fedora.html
  _scripts/instruction-widget/templates/install/opensuse.html
  _scripts/instruction-widget/templates/install/snap.html
  _scripts/instruction-widget/templates/install/ubuntu.html
Labels: area: snaps, docs
